// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAlarmChange();
void onPanicChange();
void onPartialChange();

CloudSwitch alarm;
CloudSwitch panic;
CloudSwitch partial;

void initProperties(){
  ArduinoCloud.addProperty(alarm, READWRITE, ON_CHANGE, onAlarmChange);
  ArduinoCloud.addProperty(panic, READWRITE, ON_CHANGE, onPanicChange);
  ArduinoCloud.addProperty(partial, READWRITE, ON_CHANGE, onPartialChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
