// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onArmChange();
void onDisarmChange();
void onHomeChange();
void onPanicChange();

CloudSwitch arm;
CloudSwitch disarm;
CloudSwitch home;
CloudSwitch panic;

void initProperties(){

  ArduinoCloud.addProperty(arm, READWRITE, ON_CHANGE, onArmChange);
  ArduinoCloud.addProperty(disarm, READWRITE, ON_CHANGE, onDisarmChange);
  ArduinoCloud.addProperty(home, READWRITE, ON_CHANGE, onHomeChange);
  ArduinoCloud.addProperty(panic, READWRITE, ON_CHANGE, onPanicChange);


  ArduinoCloud.updateCertificate(CERT_AUTHORITY, CERT_SERIAL, CERT_NOT_BEFORE, CERT_NOT_AFTER, CERT_SIGNATURE_RS);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
